set(HWSOURCES
	SIMMProgrammer/hal/at90usb646/LUFA/Common/Architectures.h
	SIMMProgrammer/hal/at90usb646/LUFA/Common/ArchitectureSpecific.h
	SIMMProgrammer/hal/at90usb646/LUFA/Common/Attributes.h
	SIMMProgrammer/hal/at90usb646/LUFA/Common/BoardTypes.h
	SIMMProgrammer/hal/at90usb646/LUFA/Common/Common.h
	SIMMProgrammer/hal/at90usb646/LUFA/Common/CompilerSpecific.h
	SIMMProgrammer/hal/at90usb646/LUFA/Common/Endianness.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Class/Device/CDCClassDevice.c
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Class/CDCClass.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Class/Common/CDCClassCommon.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Class/Device/CDCClassDevice.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.c
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/AVR8/Device_AVR8.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.c
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/AVR8/Endpoint_AVR8.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.c
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/AVR8/EndpointStream_AVR8.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.c
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/AVR8/Host_AVR8.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/AVR8/OTG_AVR8.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.c
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/AVR8/Pipe_AVR8.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.c
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/AVR8/PipeStream_AVR8.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.c
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/AVR8/USBController_AVR8.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.c
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/AVR8/USBInterrupt_AVR8.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/ConfigDescriptor.c
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/ConfigDescriptor.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/DeviceStandardReq.c
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/DeviceStandardReq.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/Device.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/Endpoint.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/EndpointStream.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/Events.c
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/Events.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/Host.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/HostStandardReq.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/OTG.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/Pipe.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/PipeStream.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/StdDescriptors.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/StdRequestType.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/USBController.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/USBInterrupt.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/USBMode.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/USBTask.c
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/Core/USBTask.h
	SIMMProgrammer/hal/at90usb646/LUFA/Drivers/USB/USB.h
	SIMMProgrammer/hal/at90usb646/LUFA/Version.h
	SIMMProgrammer/hal/at90usb646/LUFAConfig.h

	SIMMProgrammer/hal/at90usb646/cdc_device_definition.c
	SIMMProgrammer/hal/at90usb646/cdc_device_definition.h
	SIMMProgrammer/hal/at90usb646/Descriptors.c
	SIMMProgrammer/hal/at90usb646/Descriptors.h
	hal/at90usb646/hardware.c
	hal/at90usb646/hardware.h
	hal/at90usb646/LUFAConfig.h
)
